version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/FizzBuzzSolution/"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"
    reviewers:
      - "ushibutatory"
