name: Build

on:
  push:
    paths:
      - src/**
      - .github/workflows/Build.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup
        uses: actions/setup-dotnet@v1
      - name: Build and Test
        run: |
          cd "${GITHUB_WORKSPACE}/${SOLUTION_DIR}/"
          dotnet build
          dotnet test --no-build
        env:
          SOLUTION_DIR: ./src/FizzBuzzSolution
